bf-backoffice/config/routes.rb
Rails.application.routes.draw do
  get 'products/index'

  get 'products/life'

  get 'products/lifetrust'

  get 'products/estateplanning'

  resources :products
  devise_for :users
  resources :clients
  get 'wiki_pages/home'

  root 'wiki_pages#home'
  get 'new_client' => 'clients#new'
  get 'view_clients' => 'clients#index'
  get 'products' => 'products#index'
  get 'lifetrust' => 'products#lifetrust'

end

bf-backoffice/app/models/client.rb
class Client < ActiveRecord::Base
end

bf-backoffice/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

bf-backoffice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bf-backoffice/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :surname, :email, :telephone_number, :address1, :address2, :town, :post_code, :county, :country, :product, :status, :notes, :agent_number)
    end
end

bf-backoffice/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def life
  end

  def lifetrust
  end

  def estateplanning
  end
end

bf-backoffice/app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end
end

bf-backoffice/app/helpers/application_helper.rb
module ApplicationHelper
end

bf-backoffice/app/helpers/clients_helper.rb
module ClientsHelper
end

bf-backoffice/app/helpers/products_helper.rb
module ProductsHelper
end

bf-backoffice/app/helpers/wiki_pages_helper.rb
module WikiPagesHelper
end

bf-backoffice/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone_number %><br>
    <%= f.text_field :telephone_number %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :town %><br>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :post_code %><br>
    <%= f.text_field :post_code %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :agent_number %><br>
    <%= f.number_field :agent_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bf-backoffice/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

bf-backoffice/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Telephone number</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Town</th>
      <th>Post code</th>
      <th>Country</th>
      <th>Product</th>
      <th>Status</th>
      <th>Agent number</th>
      <% if current_user.admin %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.surname %></td>
        <td><%= client.email %></td>
        <td><%= client.telephone_number %></td>
        <td><%= client.address1 %></td>
        <td><%= client.address2 %></td>
        <td><%= client.town %></td>
        <td><%= client.post_code %></td>
        <td><%= client.country %></td>
        <td><%= client.product %></td>
        <td><%= client.status %></td>
        <td><%= client.agent_number %></td>
        <% if current_user.admin %>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

bf-backoffice/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

bf-backoffice/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @client.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Telephone number:</strong>
  <%= @client.telephone_number %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @client.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @client.address2 %>
</p>

<p>
  <strong>Town:</strong>
  <%= @client.town %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @client.post_code %>
</p>

<p>
  <strong>County:</strong>
  <%= @client.county %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<p>
  <strong>Product:</strong>
  <%= @client.product %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<p>
  <strong>Agent number:</strong>
  <%= @client.agent_number %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

bf-backoffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuchananFraser Back Office</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to('Home', root_path )%></li>
            <li><%= link_to('Products', products_path )%></li>
		        <li><%= link_to('Add New Client', new_client_path )%></li>
		        <li><%= link_to('View Clients', view_clients_path )%></li>
		        <li><%= link_to('Change My Account Details', '/users/edit') %></li> 

		        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
			      <% else %>
			       <li><%= link_to('Login', new_user_session_path)  %></li>
			      <% end %>
          </ul>
        </nav>
      </div>
    </header>
	  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
    	
		  <%= yield %>
	  </div>

</body>
</html>

bf-backoffice/app/views/products/estateplanning.html.erb
<h1>Products#estateplanning</h1>
<p>Find me in app/views/products/estateplanning.html.erb</p>

bf-backoffice/app/views/products/index.html.erb
<div class="col-md-12">
	<div class="col-md-3">
		<h5>Breadcrumbs</h5>
		<%= link_to 'Placing a Life Policy in Trust', lifetrust_path %><br>
		<%= link_to 'Placing a Life Policy in Trust', lifetrust_path %><br>
		<%= link_to 'Placing a Life Policy in Trust', lifetrust_path %><br>
		<%= link_to 'Placing a Life Policy in Trust', lifetrust_path %>
	</div>
	<div class="col-md-9">

	</div>
</div>

bf-backoffice/app/views/products/life.html.erb
<h1>Products#life</h1>
<p>Find me in app/views/products/life.html.erb</p>

bf-backoffice/app/views/products/lifetrust.html.erb
<h1>Products#lifetrust</h1>
<p>Find me in app/views/products/lifetrust.html.erb</p>

bf-backoffice/app/views/wiki_pages/home.html.erb
<h1>BuchananFraser Wiki</h1>
<h5>Welcome <%= current_user.email %> </h5>
<div class="row">
	<div class="col-md-12">
		<div class="col-md-9">
			<h3>Script</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce faucibus rutrum aliquet. Donec tincidunt feugiat consequat. Morbi facilisis neque sit amet enim varius, sit amet aliquam odio vestibulum. In fermentum, ligula vel porta pellentesque, velit lacus auctor enim, vel congue ipsum metus ut tortor. Phasellus at leo ornare, lacinia nunc ut, interdum nulla. Aenean ut gravida mauris, ac feugiat urna. Ut tristique ante et eros varius, non maximus purus cursus. Vivamus rhoncus tortor lacus, ac faucibus velit aliquet a. Integer convallis erat sed massa condimentum, in convallis nisl molestie. Quisque quis lectus magna. Morbi at ultricies ligula. Maecenas ex dolor, lacinia non pharetra sed, rhoncus ac purus. Aliquam erat volutpat. Morbi gravida facilisis sagittis. Mauris sodales velit eget dolor scelerisque efficitur. Pellentesque ultrices ut mauris nec efficitur.<br><br>

			Suspendisse dignissim feugiat porta. Aliquam vitae nulla nunc. Nunc et placerat nulla. Duis semper pellentesque urna, sit amet tempor eros luctus et. Vivamus vehicula non massa id ultrices. Nullam iaculis nec est eu rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur tristique, risus et mattis mattis, dolor orci ultricies dolor, nec vulputate massa est in justo. Morbi imperdiet ex vel ultrices venenatis. Ut scelerisque dignissim nisl, vel tincidunt quam tempor a. Nunc vel pulvinar lacus. Nulla imperdiet odio in fringilla rutrum.<br><br>

			Praesent eget efficitur nulla. Donec aliquet, nisi eget ornare congue, metus magna pretium quam, at posuere dui metus ac lorem. Vestibulum commodo lorem elit. Morbi gravida neque sit amet euismod scelerisque. Phasellus mauris nisi, ultrices sit amet libero ac, efficitur congue nulla. Aliquam rutrum pharetra massa. Etiam eget elementum lorem, eu ultricies eros. Nunc vulputate sapien lacus, vitae facilisis turpis ullamcorper a. Donec ornare magna at elementum dictum. Aliquam euismod diam libero, at tempus quam laoreet nec. Vivamus malesuada est non neque luctus, a interdum dui lacinia. Curabitur vehicula venenatis iaculis. Nunc sit amet erat elementum, tincidunt velit a, sodales tortor. Fusce luctus tincidunt sapien quis hendrerit.<br><br>

			Integer velit ipsum, venenatis id elit sit amet, volutpat dictum neque. Sed blandit purus sit amet condimentum gravida. Suspendisse eget justo porta, auctor justo in, commodo dolor. Curabitur tempor erat ipsum, non pellentesque diam fringilla non. Sed varius tortor massa, sed condimentum leo vulputate quis. Integer a risus ullamcorper, pulvinar felis eget, egestas lacus. Integer suscipit arcu eget sem dignissim, eu finibus ex placerat. Curabitur a risus in leo porta pulvinar. Curabitur iaculis neque id orci tempus, nec gravida ante pharetra. Suspendisse sed tempus justo. Sed varius arcu sit amet lorem semper laoreet. Mauris consequat ultricies aliquam. Etiam id tristique mi, id porttitor ligula. Sed hendrerit, arcu et elementum viverra, diam augue viverra quam, sed finibus felis tellus sit amet ipsum.</p>

			<hr>

			<h3>Useful Links</h3>
			<a href='http://www.legalandgeneral.com/_resources/pdfs/life-cover/trust-information/Discretionary-Trust-Form.pdf'>Legal and General</a>

			<hr>

			<h3>My Active Cases</h3>

		</div>
		<div class="col-md-3">
			<h3>FAQ's</h3>
			<ul>
			<li><strong>Who is the settlor?</strong><br>
			The person or people who set up the trust. They should be 18 or over and of sound mind.</li>
			<li><strong>Who can be a trustee?</strong><br>
			You can appoint any adult who is of sound mind as a trustee. You can also appoint a trust company. There are a number of things to bear in mind when you appoint your trustees and you should speak to your own professional advisers about this. With the protection trusts, as the settlor, you automatically become a trustee. We recommend that you appoint at least one other trustee.</li>
			<li><strong>Who has the power to change the
			beneficiaries under the trust?</strong><br>
			As the settlor, you can choose who will benefit from
			the trust when you set it up. You can also change the beneficiaries. When you die, any surviving settlor can change the beneficiaries. When all the settlors have died, the trustees can change the beneficiaries until the trust ends.</li>
			<li><strong>Can a husband and wife or civil partners each take out their own trust arrangements?</strong><br>
			Yes, but we recommend that you discuss this with professional advisers first as it could remove any inheritance tax advantage.</li>
			<li><strong>Can a husband and wife or civil
			partners establish a trust jointly?</strong><br>
			Yes, you can do this with the Aviva Discretionary Gift
			Trust (Protection) or the Aviva Survivor Trust. The Aviva Married Women’s Property Act Trust is only suitable for life insurance plans that only cover one person.</li>
			<li><strong>Can I use the trust with existing life
			insurance plans?</strong><br>
			Yes, you can put an existing life insurance plan under trust using the Aviva Discretionary Gift Trust (Protection) or the Aviva Survivor Trust.</li>
			</ul>
		</div>
	</div>
</div>